name: select-matching-issues
description: Selects issues matching a query
inputs:
  format:
    default: raw
    description: Format to use when outputting the list of issues to the file
  path:
    default: __matching-issues.txt
    description: Path to store the resulting list of issues
  query:
    description: Query to use to search for matching issues
    required: true
  token:
    description: Token to use to execute the search
    required: true
outputs:
  path:
    description: Path to file containing the list of issues
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: blue
  icon: crosshair
